# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
trigger:
  - main
pr:
  - main

variables:
  GO_VERSION: 1.13
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: UnitTest
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 30
    steps:
    - template: azp-dependencies.yml
    - checkout: self
    - script: make checks && make unit-test
      displayName: Run checks and unit test
    - script: bash <(curl https://codecov.io/bash) -t $CODECOV_UPLOAD_TOKEN
      env:
        CODECOV_UPLOAD_TOKEN: $(CODECOV_UPLOAD_TOKEN)
      displayName: Upload coverage to Codecov

  - job: Publish
    dependsOn:
      - UnitTest
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          function logout {
            docker logout
          }
          trap logout EXIT
          source ci/version_var.sh
          echo $DOCKER_PASSWORD | docker login ghcr.io --username $DOCKER_USER --password-stdin
          make sidetree-ipfs-docker
          docker tag ghcr.io/trustbloc/sidetree-ipfs:latest ${SIDETREE_IPFS_PKG}:${SIDETREE_IPFS_TAG}
          docker push ${SIDETREE_IPFS_PKG}:${SIDETREE_IPFS_TAG}
        env:
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
